### PR TITLE
Added Symfony 4 support

### PR DESCRIPTION
**Pull request by bobvandevijver**
This depends on https://github.com/symfony2admingenerator/FormBundle/pull/11 being merged and released as version 1.5.

### CODE REVIEW

**Comment by bobvandevijver** [comment]
@tobias-93 It is possible, but I choose to keep them for two reasons:
- BC for users who do not use the supplied twig files
- A simple diff between the files shows exactly what is fixed, for whenever the version will be updated.

So, I would keep them.

**Comment by tobias-93** [comment]
Ok, but it will break BC for people that don't use the supplied twig files but do use the customization CSS (for select2). So maybe add the customizations to `Resources/public/select2/css/select2.fixed.css` or make a `Resources/public/select2/css/select2.fixed.custom.css`?

**Comment by bobvandevijver** [comment]
@tobias-93 Fair enough, it's updated now

**Comment by tobias-93** [comment]
Thanks @bobvandevijver!

**Pull request merged**
