### PR TITLE
Row fluid class does not exists in BS3, removed.

### PR DESCRIPTION
**Pull request by TheCelavi**
BS3 removed 'row-fluid' class, someone missed this one to remove...

### CODE REVIEW

**Comment by bobvandevijver** [comment]
When I [search](https://github.com/symfony2admingenerator/FormExtensionsBundle/search?q=row-fluid&type=Code&utf8=%E2%9C%93) for the `row-fluid` class, I find some more references in the current code.

Can you confirm that this change does not break behavior, and maybe check if the others ones also need to be removed?

**Comment by TheCelavi** [comment]
Well, I do not know how well you are familiar with BS2 and BS3.

BS2 had row and row-fluid classes.

BS3 (removed) row-fluid class.

Since current version uses BS3 only, all row-fluid classes should be replaced with row only.

If you want me to, I can go trough code, check usages and fix them.

But I can guarantee to you 100% - 'row-fluid' removal will not have any negative impact.

**Comment by bobvandevijver** [comment]
Sure, but I'm more worried about the new row class as that will probably change the layout due to the CSS-rules that will be defined now. But then again, it should not be much.

Can you check the other usages to ensure that this is fixed once and for all? :+1:

**Comment by TheCelavi** [comment]
Of course.

**Comment by TheCelavi** [comment]
All cleaned up. It seams that this was only related to single upload.

**Comment by bobvandevijver** [comment]
Looks good, many thanks!

**Pull request merged**
