### PR TITLE
fix image asset when object is null

### PR DESCRIPTION
**Pull request by montabou**
As explained here https://github.com/symfony2admingenerator/FormExtensionsBundle/issues/57#issuecomment-194174827
Image asset does not work when object is null

### CODE REVIEW

**Comment by montabou** [comment]
More info about this error.
It occurs when symfony tries to generate template for javascript with collection as the object is null $object->$getter() throws an exception.
Empty path is OK as the preview is generated with javascript when an image is selected.

**Comment by bobvandevijver** [comment]
Can you elaborate on the exact error? When do you experience the error? An object with an not-required image field, which you want to edit?

I use this field in an admingenerator, and I do not have any problems editing such an object...

**Comment by montabou** [comment]
I have a File-genarator.yml with
```
    fields:                                                                                
        file:                                                                                     
            formType: Admingenerator\FormExtensionsBundle\Form\Type\SingleUploadType
```
A Data-generator.yml with
```
    fields:                                                                                                   
        files:                                                                                                       
            label: data.files.label                                                                                  
            formType: Admingenerator\FormExtensionsBundle\Form\Type\BootstrapTableCollectionType                     
            addFormOptions:                                                                                          
                entry_type: ...Bundle\Form\Type\File\EditType                                            
                entry_options:                                                                                       
                    data_class: ...Bundle\Entity\File                                                     
                allow_add: true                                                                                      
                allow_delete: true                                                                                   
                by_reference: false
```
A Product-generator.yml with
```
   fields:               
        translations:                                                                                                          
            formType: A2lix\TranslationFormBundle\Form\Type\TranslationsType                                         
            addFormOptions:                                                                                          
                fields:                                                                                                                
                    data:                                                                                            
                        label: product.translations.data.label                                                       
                        field_type: ...Bundle\Form\Type\Data\EditType                                    
                        data_class: ...Bundle\Entity\Data   
```
And a last genarator.yml where the error occurs with
```
    fields:       
        products:                                                                                                          
            formType: Admingenerator\FormExtensionsBundle\Form\Type\BootstrapTableCollectionType                     
            addFormOptions:                                                                                          
                entry_type: ...Bundle\Form\Type\Product\EditType                                         
                entry_options:                                                                                       
                    data_class: ...Bundle\Entity\Product                                                  
                allow_add: true                                                                                      
                allow_delete: true                                                                                   
                by_reference: false   
```

You think that the error is linked to an other stuff ? Maybe A2lix ?
I don't know how I can test that.

**Comment by TheCelavi** [comment]
I can confirm this error as well.

Collection of images (SingleUploadType is used) is embedded into master form via collection (BootstrapTableCollectionType per example).

As you all know -> Symfony creates a "data-prototype" (see: http://symfony.com/doc/current/cookbook/form/form_collections.html) attribute with prototype html. In order to create that prototype HTML, it renders empty form type (in this case -> SingleUploadType). Single upload type expects object or null (I think...). Issue is that when this prototype is generated, object is null, so we have issue here:

symfony2admingenerator/form-extensions-bundle/Admingenerator/FormExtensionsBundle/Resources/views/Form/SingleUpload/controls.html.twig, line no: 12.

Fix should be fairly simple: line no 8: {% if downloadable and object is not null %}

I do not agree that fix is where this PR proposes. Template should render link for download if object exists, it should not render download link to empty path (i.e. "").

**Comment by montabou** [comment]
I've updated the PR thanks to your comment. I also think it's data-prototype problem and your correction is smarter than my first one.

**Comment by bobvandevijver** [comment]
Okay, I get they use-case now! Can you squash the commit into a single one and remove the change in `Twig/Extension/ImageAssetsExtension.php`? Than I will merge it :+1:

**Comment by montabou** [comment]
Arf I did a other PR as I did not manage correctly this PR

**Pull request closed without merging**
