### PR TITLE
Add a way to disable select form extension

### PR DESCRIPTION
**Pull request by loostro**
Use form extension for expanded choice fields unless class is explicitly set.

### CODE REVIEW

**Comment by loostro** [comment]
Resolves issue #17

**Comment by bobvandevijver** [comment]
@loostro Unfortunately, this is not enough, as the form_js function still creates the javascript for the form field, as it does not check the class. See [form_js.html.twig#335](https://github.com/symfony2admingenerator/FormExtensionsBundle/blob/master/Resources/views/Form/form_js.html.twig#L335).

**Comment by loostro** [comment]
@bobvandevijver updated `form_js`

**Comment by bobvandevijver** [comment]
Works for me! :+1:

**Comment by loostro** [comment]
@bobvandevijver merged, thanks

**Pull request merged**
