### PR TITLE
Added Serbian latin translation, translation domain to BootstrapCollectionType

### PR DESCRIPTION
**Pull request by TheCelavi**
Added Serbian latin translation, translation domain to BootstrapCollectionType

### CODE REVIEW

**Comment by bobvandevijver** [comment]
Hi @TheCelavi 

Please remove the translation domain, then the added translations can be merged. We do not use the translation domain by default in this bundle.

**Comment by TheCelavi** [comment]
Are you sure? 

See per example: /FormExtensionsBundle/Resources/views/Form/form_html.html.twig line no. 48. From where this "translation_domain" comes from?

Moreover, I have a strange bug, everything is translated in collection except this message "s2a_bootstrap_collection.new_label" - I thought that that is a result because default translation domain is missing so it tries to find message in default "messages" catalogue.

**Comment by TheCelavi** [comment]
Ok, removed, will try to reproduce a bug and send you a details. For now, here is a translation only.

**Comment by bobvandevijver** [comment]
@TheCelavi Something went wrong, the changeset is not only the new translations file, can you check that?

**Comment by TheCelavi** [comment]
Yes - I am an idiot, made a typo, sorry :( wont happen again :(

Removed translation domain, returned new label.

Sorry again, I was in hurry.

**Comment by bobvandevijver** [comment]
No problem, thanks for the translations!

When you have more details on the translation domain issue, please open an issue :)

**Pull request merged**
